 # docker-compose.yaml
version: '3.8'
services:
  jenkins:
    build:
      context: .
    privileged: true
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    networks:
      - jenkins
    volumes:
      - ./data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  jenkins:
    driver: bridge